### ISSUE TITLE
Type error when consuming @airlookjs/loudness as typescript 

### ISSUE THREAD

**Issue by smukkejohan** [airlookjs/airlookjs#102]
node_modules/.pnpm/@airlookjs+loudness@1.7.0/node_modules/@airlookjs/loudness/src/app.d.ts:2:96 - error TS2304: Cannot find name 'FastifyInstance'.

**Comment by olekristensen** [comment]
Can this one be closed?

**Comment by smukkejohan** [comment]
Yes its fixed in #103.
